name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        env:
          GITHUB_JSON: ${{ toJSON(github) }}
        run: |
          printf '  \e[31m%s\e[0m\n' 'indented color'
          printf '\e[31m  %s\e[0m\n' 'indented but color at start'
          printf '  \e[31m%s\e[0m    \e[32m%s\e[0m\n' 'indented color' 'more color'
          printf '\t\e[31m%s\e[0m\t\e[32m%s\e[0m\n' 'indented with tab' 'more color'
          for i in 200{{0..9},{A..B}}
          do
            printf -v space "\\U$i"
            printf 'colored JSON with spaces replaced with %s\n' "\\U$i"
            printf %s "$GITHUB_JSON" | jq -C . | sed "s/ /$space/g"
          done
